/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GridApp.view.MyContainer', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.grid.feature.RowBody',
        'Ext.selection.CellModel',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.button.Button'
    ],

    height: 472,

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    height: 451,
                    itemId: 'runsGrid',
                    width: '75%',
                    title: 'Jooksud',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Nimi'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'Aasta'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Tulemus'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Vanuseklass'
                        }
                    ],
                    features: [
                        {
                            ftype: 'rowbody'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CellModel', {

                    })
                },
                {
                    xtype: 'form',
                    itemId: 'defForm',
                    width: '25%',
                    defaults: {
                        labelWidth: 60
                    },
                    bodyPadding: 10,
                    title: 'Detailid',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Nimi'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'Aasta'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Tulemus'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Vanuseklass',
                            labelWidth: 80
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'Jooksu number'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'Stardi positsioon'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Sünniaeg'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Maakond'
                        },
                        {
                            xtype: 'container',
                            margin: 0,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'save',
                                    margin: '0 5 0 5',
                                    text: 'Salvesta'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'reset',
                                    margin: '0 5 0 5',
                                    text: 'Tühjenda'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'deselect',
                                    margin: '0 5 0 5',
                                    text: 'Tühista'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});